package repository

import (
	//sqlc_store "app/internal/store/sqlc"
	"context"
)

// Store defines all functions to execute db queries and transactions
type Store interface {
	AttachNativeConn(ctx context.Context, addr string, maxConns int, maxConnIdleTime string) error
	GetNativeConn() interface{}
	// For SQLC
	// You must import "app/internal/store/sqlc" package
	//sqlc_store.Querier //Querier code generated by sqlc
	//Close() error

	//Custom
}

/*
func ExecTx(db *sql.DB, ctx context.Context, fn func(*sqlc_store.Queries) error) error {
	tx, err := db.BeginTx(ctx, nil)
	if err != nil {
		return err
	}

	q := sqlc_store.New(tx)
	err = fn(q)
	if err != nil {
		if rbErr := tx.Rollback(); rbErr != nil {
			return fmt.Errorf("tx err: %v, rb err: %v", err, rbErr)
		}
		return err
	}

	return tx.Commit()
}
*/
